services:
  pgdb:
    profiles: ["dev"]
    container_name: pgdb_remi
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  elasticsearch:
    container_name: search
    image: elasticsearch:8.4.1
    environment:
      - cluster.name=remi-elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - pgdb