# Generated by Django 4.1.1 on 2022-09-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
