# Generated by Django 4.1.1 on 2022-09-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remi', '0002_alter_product_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
