# Generated by Django 4.1.1 on 2022-09-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated',
        ),
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
