# Generated by Django 4.1.1 on 2022-09-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_created_remove_sale_updated_sale_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='price_sale',
        ),
    ]
