# Generated by Django 4.1.1 on 2022-09-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remi', '0003_alter_product_price_sale'),
        ('sales', '0003_remove_saleproduct_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='remi.product'),
        ),
    ]
